name: Startupswagger.io
favicon: null
layout_spectrum: 0.14379
typography_spectrum: 0.22336
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#808143'
    - '#c32b5d'
    - '#003b83'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
